=== MikelUrlezaga/MikelUrlezagaPrivau/Lenguaiak/Azterketa eginda/03-liburuak.dtd
<!ELEMENT liburuak (liburua+)>
<!ELEMENT liburua (
    izenburua, 
    egilea, 
    editoriala, 
    kategoria*,
    urtea, 
    orrialdeak?, 
    hizkuntza)>
<!ATTLIST liburua isbn CDATA #REQUIRED>
<!ELEMENT izenburua (#PCDATA)>
<!ELEMENT egilea (#PCDATA)>
<!ELEMENT editoriala (#PCDATA)>
<!ELEMENT kategoria (#PCDATA)>
<!ELEMENT urtea (#PCDATA)>
<!ELEMENT orrialdeak (#PCDATA)>
<!ELEMENT hizkuntza EMPTY>
<!ATTLIST hizkuntza lang (en|es|eus) #REQUIRED>

=== MikelUrlezaga/MikelUrlezagaPrivau/Lenguaiak/Azterketa eginda/03-liburuak.xml
<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE liburuak SYSTEM "03-liburuak.dtd">
<liburuak>
	<liburua isbn="9788481362596">
		<izenburua>Eraztunen jauna</izenburua>
		<egilea>J.R.R. Tolkien</egilea>
		<editoriala>Minotauro</editoriala>
		<kategoria>Fikzioa</kategoria>
		<urtea>1954</urtea>
		<orrialdeak>542</orrialdeak>
		<hizkuntza lang="eus"></hizkuntza>
	</liburua>
	<liburua isbn='9780140173154'>
		<izenburua>Maus</izenburua>
		<egilea>Art Spiegelman</egilea>
		<editoriala>Reservoir Books</editoriala>
		<kategoria>Drama</kategoria>
		<kategoria>Autobiografikoa</kategoria>
		<kategoria>Komikia</kategoria>
		<urtea>1991</urtea>
		<hizkuntza lang='en'/>
	</liburua>
	<liburua isbn="9881155173127">
		<izenburua>1984</izenburua>
		<egilea>George Orwell</egilea>
		<editoriala>Secker and Warburg</editoriala>
		<urtea>1949</urtea>
		<hizkuntza lang="en" />
	</liburua>
</liburuak>
