=== MikelUrlezaga/MikelUrlezagaPrivau/Lenguaiak/Azterketa eginda/04-animaliak-v2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- Erro elementua -->
    <xsd:element name="animaliak" type="TAnimaliak" />

    <xsd:complexType name="TAnimaliak">
        <xsd:sequence>
            <!-- Hurrengoak behin baino gehiagotan agertu daitezke -->
            <xsd:element name="hugaztuna" maxOccurs="unbounded" type="THugaztuna"/>
            <xsd:element name="hegaztia" maxOccurs="unbounded" type="THegaztia" />
            <xsd:element name="narrastia" maxOccurs="unbounded" type="TNarrastia" />
            <!-- Arraina elementua ez da zertan agertu behar -->
            <xsd:element name="arraina" minOccurs="0" maxOccurs="unbounded" type="TAnimalia"/>   
        </xsd:sequence>
    </xsd:complexType>

    <!-- Animaliek partekatzen dituzten ezaugarri guztiak dituen super-klasea -->
    <xsd:complexType name="TAnimalia">
        <xsd:sequence>
            <xsd:element name="izena" type="xsd:string"/>
            <xsd:element name="habitatea" type="xsd:string"/>
            <xsd:element name="elikatzea" type="TElikatzea"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="TId" use="required" />
    </xsd:complexType>

    <!-- 
        TAnimalia super-klasetik ezaugarriak hedatzen dituen azpi-klasea 
        + hanka_zenbakia (int) ezaugarri propioa
    -->
    <xsd:complexType name="THugaztuna">
        <xsd:complexContent>
            <xsd:extension base="TAnimalia">
                <xsd:sequence>
                    <xsd:element name="hanka_zenbakia" type="xsd:int" minOccurs="0" default="4"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!-- 
        TAnimalia super-klasetik ezaugarriak hedatzen dituen azpi-klasea 
        + hegalaria (boolean) ezaugarri propioa
    -->
    <xsd:complexType name="THegaztia">
        <xsd:complexContent>
            <xsd:extension base="TAnimalia">
                <xsd:sequence>
                    <xsd:element name="hegalaria" type="xsd:boolean" />
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>    

    <!-- 
        TAnimalia super-klasetik ezaugarriak hedatzen dituen azpi-klasea 
        + pozoitsua (boolean) ezaugarri propioa
    -->
    <xsd:complexType name="TNarrastia">
        <xsd:complexContent>
            <xsd:extension base="TAnimalia">
                <xsd:sequence>
                    <xsd:element name="pozoitsua" type="xsd:boolean" />
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>   

    <!-- Testu-kate mugatuak zehazten dituen datu mota -->
    <xsd:simpleType name="TElikatzea">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Haragijalea" />
            <xsd:enumeration value="Belarjalea" />
            <xsd:enumeration value="Omniboroa" />
            <!--
            <xsd:pattern value="(Haragijalea|Belarjalea|Omniboroa)" />
            -->
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Zenbaki mugatuak zehazten dituen datu mota -->
    <xsd:simpleType name="TId">
        <xsd:restriction base="xsd:int">
            <!--
            <xsd:minInclusive value="10"/>
            <xsd:maxInclusive value="99"/>
            -->
            <xsd:pattern value="[0-9]{2}"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== MikelUrlezaga/MikelUrlezagaPrivau/Lenguaiak/Azterketa eginda/04-animaliak.xml
<?xml version="1.0" encoding="UTF-8"?>
<animaliak 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="04-animaliak-v2.xsd">
    <hugaztuna id="10">
        <izena>Lehoia</izena>
        <habitatea>Sabana</habitatea>
        <elikatzea>Haragijalea</elikatzea>
    </hugaztuna>
    <hugaztuna id="11">
        <izena>Kangurua</izena>
        <habitatea>Eremi lehorrak</habitatea>
        <elikatzea>Belarjalea</elikatzea>
        <hanka_zenbakia>2</hanka_zenbakia>
    </hugaztuna>
    <hegaztia id="20">
        <izena>Arranoa</izena>
        <habitatea>Basoak eta mendiak</habitatea>
        <elikatzea>Haragijalea</elikatzea>
        <hegalaria>true</hegalaria>
    </hegaztia>
    <hegaztia id="21">
        <izena>Ostruka</izena>
        <habitatea>Sabana</habitatea>
        <elikatzea>Omniboroa</elikatzea>
        <hegalaria>false</hegalaria>
    </hegaztia>        
    <narrastia id="30">
        <izena>Serpiente</izena>
        <habitatea>Basoak eta mendiak</habitatea>
        <elikatzea>Haragijalea</elikatzea>
        <pozoitsua>true</pozoitsua>
    </narrastia>     
    <narrastia id="31">
        <izena>Kokodriloa</izena>
        <habitatea>Ibaiak eta zingirak</habitatea>
        <elikatzea>Haragijalea</elikatzea>
        <pozoitsua>false</pozoitsua>
    </narrastia>            
</animaliak>
