=== MikelUrlezaga/MikelUrlezagaPrivau/LO DE CLASE/MIKEL_URLEZAGA_PASCUAL/baratza.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="baratza" type="TBaratza"/>

    <xs:complexType name="TBaratza">
        <xs:sequence>
            <xs:element name="landarea" type="TLandarea" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="barazkia" type="TBarazkia" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TLandarea">
            <xs:sequence>
                <xs:element name="izena" type="xs:string" />
                <xs:element name="familia" type="xs:string" />
                <xs:element name="jatorria" type="xs:string" />
                <xs:element name="kolorea" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="code" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="TBarazkia">
        <xs:sequence>
            <xs:element name="izena" type="xs:string" />
            <xs:element name="familia" type="xs:string" />
            <xs:element name="jatorria" type="xs:string" />
            <xs:element name="kolorea" type="xs:string" />
            <xs:element name="noiz_landatu" type="TLandatu" />
            <xs:element name="noiz_jaso" type="TJaso" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="TLandatu">
        <xs:sequence>
            <xs:element name="hilabetea" type="THilabete" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TJaso">
        <xs:sequence>
            <xs:element name="hilabetea" type="THilabete" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="THilabete">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Urtarrila"/>
            <xs:enumeration value="Otsaila"/>
            <xs:enumeration value="Martzoa"/>
            <xs:enumeration value="Apirila"/>
            <xs:enumeration value="Maiatza"/>
            <xs:enumeration value="Ekaina"/>
            <xs:enumeration value="Uztaila"/>
            <xs:enumeration value="Abuztua"/>
            <xs:enumeration value="Iraila"/>
            <xs:enumeration value="Urria"/>
            <xs:enumeration value="Azaroa"/>
            <xs:enumeration value="Abendua"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MikelUrlezaga/MikelUrlezagaPrivau/LO DE CLASE/MIKEL_URLEZAGA_PASCUAL/baratza.xml
<?xml version="1.0" encoding="UTF-8"?>
<baratza xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="baratza.xsd">
  <landarea code="01">
    <izena>Izpilikua</izena>
    <familia>Lamiazeoa</familia>
    <jatorria>Mediterraneoa</jatorria>
    <kolorea>Morea</kolorea>
  </landarea>
  <landarea code="02">
    <izena>Menda</izena>
    <familia>Lamiazeoa</familia>
    <jatorria>Europa eta Asia</jatorria>
    <kolorea>Berdea</kolorea>
  </landarea>
  <landarea code="03">
    <izena>Erromeroa</izena>
    <familia>Lamiazeoa</familia>
    <jatorria>Mediterraneoa</jatorria>
    <kolorea>Berdea</kolorea>
  </landarea>
  <barazkia code="04">
    <izena>Tomatea</izena>
    <familia>Solanazeoa</familia>
    <jatorria>Erdi eta Hego Amerika</jatorria>
    <kolorea>Gorria</kolorea>
    <noiz_landatu>
      <hilabetea>Maiatza</hilabetea>
      <hilabetea>Ekaina</hilabetea>
    </noiz_landatu>
    <noiz_jaso>
      <hilabetea>Uztaila</hilabetea>
      <hilabetea>Abuztua</hilabetea>
      <hilabetea>Iraila</hilabetea>
      <hilabetea>Urria</hilabetea>
      <hilabetea>Azaroa</hilabetea>
    </noiz_jaso>
  </barazkia>
  <barazkia code="05">
    <izena>Leka</izena>
    <familia>Lekaduna</familia>
    <jatorria>Erdi eta Hego Amerika</jatorria>
    <kolorea>Berdea</kolorea>
    <noiz_landatu>
      <hilabetea>Maiatza</hilabetea>
      <hilabetea>Ekaina</hilabetea>
      <hilabetea>Uztaila</hilabetea>
    </noiz_landatu>
    <noiz_jaso>
      <hilabetea>Maiatza</hilabetea>
      <hilabetea>Ekaina</hilabetea>
      <hilabetea>Uztaila</hilabetea>
      <hilabetea>Abuztua</hilabetea>
      <hilabetea>Iraila</hilabetea>
      <hilabetea>Urria</hilabetea>
      <hilabetea>Azaroa</hilabetea>
    </noiz_jaso>
  </barazkia>
</baratza>
